### Create order
POST http://localhost:8080/orders
Content-Type: application/json

{
  "userId": 1,
  "products": [
    {
      "productId": 11,
      "quantity": 2
    },
    {
      "productId": 9,
      "quantity": 3
    }
  ]
}

### Get all order
GET http://localhost:8080/orders
Content-Type: application/json


### Get order by id
GET http://localhost:8080/orders/14
Content-Type: application/json


### Get order by user id
GET http://localhost:8080/orders/user/1
Content-Type: application/json
