### Create product 1
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Product 1",
  "description": "Product 1 description",
  "price": 10.0
}

### Create product 2
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Product 2",
  "description": "Product 3 description",
  "price": 15.99
}

### Create product 3
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Product 3",
  "description": "Product 3 description",
  "price": 19.99
}

### Find all products
GET http://localhost:8080/products
Content-type: application/json


### Find product by id
GET http://localhost:8080/products/9
Content-type: application/json
